### ISSUE TITLE
Is the App customizable ?

### ISSUE THREAD

**Issue by ebonan** [vannizhang/policymaps-new#32]
Compliments! Very nice application.
 I would like to have this application as a ready to use configurable app template  in agol/portal for ArcGIS  ...!
is this app customizable to use  different contents  from  agol or portal groups? 

thank you 
best regards
Enrico

**Comment by vannizhang** [comment]
@ebonan Yes, you can try to update the AGOL_GROUP_ID in the [AppConfig.ts](https://github.com/vannizhang/policymaps-new/blob/master/src/AppConfig.ts#L3) file using your own Group ID to make the app load contents from that group.

There is another repository [simple-map-browser](https://github.com/vannizhang/simple-map-browser) that you can use to get the simplified version of the Browse App on Policy Maps site, and you can update this [file](https://github.com/vannizhang/simple-map-browser/blob/master/src/constants/ArcGIS.ts) to use your own group.

Jinnan

**Comment by ebonan** [comment]
Thank you. We started to work with the simple-map-browser and we succesfully updated the group with our AGOL contents.
 Th question now is: does the app work also with enterprise portal groups and contents? 
thanks 
Enrico

**Comment by vannizhang** [comment]
@ebonan I just made a quick update to the simple-map-browser repo where you can provide your own Portal URL in this [file](https://github.com/vannizhang/simple-map-browser/blob/master/src/constants/ArcGIS.ts#L9), try to update the PORTAL_URL and APP_ID there to see if it would allow you to sign in into your portal or not. It should work but I am not 100% sure because how enterprise handles the OAuth is a bit different from arcgis.com.
